CREATE_ROOM = "CREATE_ROOM"
JOIN_ROOM = "JOIN_ROOM"
LEAVE_ROOM = "LEAVE_ROOM"
START_GAME = "START_GAME"
DISCONNECT = "DISCONNECT"

LEAVE_ROOM_SUCCESS = "LEAVE_ROOM_SUCCESS"
DISCONNECT_SUCCESS = "DISCONNECT_SUCCESS"
CREATE_ROOM_SUCCESS = "CREATE_ROOM_SUCCESS"
JOIN_ROOM_SUCCESS = "JOIN_ROOM_SUCCESS"

PLAYER1_DISCONNECTED = "PLAYER1_DISCONNECTED"
PLAYER2_DISCONNECTED = "PLAYER2_DISCONNECTED"

READY = "READY"
READY_SUCCESS = "READY_SUCCESS"
READY_ERROR = "READY_ERROR"

NOT_READY = "NOT_READY"
NOT_READY_SUCCESS = "NOT_READY_SUCCESS"
NOT_READY_ERROR = "NOT_READY_ERROR"